### ISSUE TITLE
0 in number field returns curValue as NULL

### ISSUE THREAD

**Issue by alonmich** [matfish2/vue-form-2#24]
To fix -
in compiled/components/mixins/mounted.js
add the isNumeric helper and line 87 should be: 
`if (this.value || isNumeric(this.value) || this.fieldType === 'checkbox') {`

**Comment by matfish2** [comment]
As mentioned in the docs, as of version 1 the package no longer saves the state (`curValue`) on the component, but uses `v-model` instead to sync the value from the parent component; thus behaving like a normal vue form field. To continue using the previous version, where the value is saved on the component, you can fork version 0.4 and maintain as you see fit. 

DISCLAIMER: this advice does NOT give you ownership of this or any other package I wrote.
 
EXPLANATION TO THE CONFUSED READER: the douchebag who opened this issue was my employer. I wrote all the packages under my Github account on my free-time, at home, and on my personal computer, without his knowledge. I (foolishly) allowed him usage of those packages, thus saving him immense amounts of time and money. As a thank you, he now demands under threats of a legal suit, that I will relinquish ownership of those packages and pass it to the company. What a stand-up guy, right? At least he thinks so. According to a letter I recently recieved from him, I should be forever grateful that he agreed to take me under his wings, and allowed me to bask in the sun of his glorious enterprise. Oh, you glorified master and lofty saviour, whose benevolence is spread accross the very fabric of my life. How could I ever thank you for being the opportunsitic, self-righteous, conniving, revolting capitalistic pig that your are?  

Before you continue on your way to the court with a burning feeling of betrayal and need for revenge, I would urge you to consider the following questions:

1. What has changed that prompts this lawsuit now? The packages have been registered under my name for years. How did me leaving the company suddenly made it lose 2 milliion NIS (the amount he is threatning to sue). 
2. The packages are open-source, which means you - and everybody else - can do whatever you like with the code. So what the fuck is your problem?
3. What would happen to the immense user-base of those packages, when they try to update the package after your supposed glorious victory? Will they get a "package not found. Taken by greedy douchebag?" error?
4. Who would maintain the packages? You? Your new developer (may God have mercy on his soul)?
5. What about changes that happened after I left. This package being a prime example. Are you entitled to those as well?

Oh, and one more thing. I am not evading you. I know it is hard for an egomaniac such as yourself to understand, but I ignore you because I actually believe that justice is on my side. I have no obligation whatsoever to help you steal what is lawfully and morally mine. You already stole enough.
